# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Common

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
jobs:

  test:
    name: Check Up-To-Date
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.36.4"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: generate Readme
        run: deno task buildReadme
      - name: format code
        run: deno task format
      - name: check readme uptodate and code formatted
        run: git diff --exit-code
      - run: cp ./ci/generated.ts ./src/
      - run: deno task check

  build_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.36.4"
      - run: deno task ci:buildNpm ${{inputs.version}}
      - run: zip build.zip -r npm
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip