# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  create:

jobs:
  build:
    if: |
      github.ref_type	== 'tag' && startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.36.4"
      - run: deno run --allow-all ./scripts/build_npm.ts ${{github.ref_name}}
      - run: cd npm && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REPOSITORY_ACCESS_TOKEN}}